name: flutter_show_case_wizard
description: "A new Flutter project."

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  showcaseview:
    git:
      url: https://github.com/bracinho2/flutter_showcaseview_with_indicators.git
      ref: master
   
  cupertino_icons: ^1.0.6
  flutter_modular: 5.0.3
  flutter_bloc: ^8.1.4

dev_dependencies:
  flutter_test:
    sdk: flutter
 
  flutter_lints: ^3.0.0

flutter:
  
  uses-material-design: true